### PR TITLE
Dispatcher

### PR DESCRIPTION
**Pull request by josephbuchma**
Quick backward-compatible fix for #3

### CODE REVIEW

**Comment by danilopolani** [comment]
Mutex seems a nice solution. How would you apply the new code to the existing example?

**Comment by danilopolani** [comment]
@josephbuchma

**Comment by josephbuchma** [comment]
@danilopolani  something like this

```go

var gocial = gocialite.NewDispatcher()

func main() {
	router := gin.Default()

	router.GET("/auth/github", redirectHandler)
	router.GET("/auth/github/callback", callbackHandler)

	router.Run("127.0.0.1:9090")
}

// Redirect to correct oAuth URL
func redirectHandler(c *gin.Context) {
	authURL := gocial.New().Driver("github"). // Set provider
		Scopes([]string{"public_repo"}). // Set optional scope(s)
		Redirect( // 
			"xxxxxxxxxxxxxx", // Client ID
			"xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx", // Client Secret
			"http://localhost:9090/auth/github/callback", // Redirect URL
		)

	// Redirect with authURL
	c.Redirect(http.StatusFound, authURL) // Redirect with 302 HTTP code
}

// Redirect to correct oAuth URL
// Handle callback of provider
func callbackHandler(c *gin.Context) {
	// Retrieve query params for code and state
	code := c.Query("code")
	state := c.Query("state")

	// Handle callback and check for errors
	user, token, err := gocial.Handle(state, code)
	if err != nil {
		c.Writer.Write([]byte("Error: " + err.Error()))
		return
	}

        // Print in terminal user information
	fmt.Printf("User: %#v, Token: %#v", user, token)
 
	// If no errors, show a success message
	c.Writer.Write([]byte("Welcome, " + user.FullName))
}
```

**Comment by danilopolani** [comment]
It works like a charm, thank you a lot! Merged

**Pull request merged**
